name = "onedrive-cf-index-ng"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-11-22"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "ONEDRIVE_CF_INDEX_KV"
id = "4b10dd386b3942fcbc3517fb918447f0"
